created: 2026-04-06T11:35:09.596Z
updated: 2026-04-06T11:35:19.680Z
update_count: 2
last_field: diagram
kind: nested-class
title: observability
children:
  - html-report
  - log-file
  - obs-init
  - obs-logger
  - token-count
parentPath: []
