created: 2026-04-06T11:31:49.175Z
updated: 2026-04-06T11:31:56.960Z
update_count: 2
last_field: diagram
kind: nested-class
title: repl-screen
children:
  - messages
  - permission-modal
  - plan-modal
  - prompt-input
  - spinner
  - verify-modal
parentPath: []
