created: 2026-04-06T11:34:44.441Z
updated: 2026-04-06T11:34:51.207Z
update_count: 2
last_field: diagram
kind: nested-class
title: hooks
children:
  - hook-events
  - hook-executor
  - hook-registry
  - hook-settings
  - hook-types
parentPath: []
