created: 2026-04-06T11:35:56.443Z
updated: 2026-04-06T11:36:05.884Z
update_count: 2
last_field: diagram
kind: nested-class
title: memdir
children:
  - backends
  - memory-age
  - memory-dir
  - memory-scan
  - type-registry
parentPath: []
